config/routes.rb
Review::Application.routes.draw do  
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/modern',  to: 'static_pages#modern',  via: 'get'
  match '/modern_retry',  to: 'static_pages#modern_retry',  via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  validates :content, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
    render text: "hello, world!"
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render action: 'show', status: :created, location: @micropost }
      else
        format.html { render action: 'new' }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def modern
    render layout: 'modern_layout'
  end
  
  def modern_retry
    render layout: 'modern_layout'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    %a{href: "http://railstutorial.jp"} Rails Tutorial
    by Michael Hartl
  %nav
    %ul
      %li=link_to "About",   about_path
      %li=link_to "Contact", contact_path
      %li<
        %a{href: "http://news.railstutorial.jp/"} News

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to "sample app",root_path,id:"logo"
      %nav
        %ul.nav.pull-right
          %li
            = link_to "Home",root_path
          %li= link_to "Help",help_path
          %li= link_to "Sign in",'#'

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title #{full_title(yield(:title))}
    = stylesheet_link_tag    "application", media: "all", |
      "data-turbolinks-track" => true                     |
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container
      = yield
      = render 'layouts/footer'

app/views/layouts/modern_layout.html.haml
!!!
%html
  %head
    %title Sample App
    = stylesheet_link_tag    "application", media: "all", |
      "data-turbolinks-track" => true                     |
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    = yield

app/views/microposts/_form.html.haml
= form_for @micropost do |f|
  - if @micropost.errors.any?
    #error_explanation
      %h2= "#{pluralize(@micropost.errors.count, "error")} prohibited this micropost from being saved:"
      %ul
        - @micropost.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :content
    = f.text_field :content
  .field
    = f.label :user_id
    = f.number_field :user_id
  .actions
    = f.submit 'Save'

app/views/microposts/edit.html.haml
%h1 Editing micropost

= render 'form'

= link_to 'Show', @micropost
\|
= link_to 'Back', microposts_path

app/views/microposts/index.html.haml
%h1 Listing microposts

%table
  %thead
    %tr
      %th Content
      %th User
      %th
      %th
      %th

  %tbody
    - @microposts.each do |micropost|
      %tr
        %td= micropost.content
        %td= micropost.user_id
        %td= link_to 'Show', micropost
        %td= link_to 'Edit', edit_micropost_path(micropost)
        %td= link_to 'Destroy', micropost, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Micropost', new_micropost_path

app/views/microposts/new.html.haml
%h1 New micropost

= render 'form'

= link_to 'Back', microposts_path

app/views/microposts/show.html.haml
%p#notice= notice

%p
  %b Content:
  = @micropost.content
%p
  %b User:
  = @micropost.user_id

= link_to 'Edit', edit_micropost_path(@micropost)
\|
= link_to 'Back', microposts_path

app/views/static_pages/about.html.haml
%h1 About Us
%p
  The
  %a{href: "http://railstutorial.org/"} Ruby on Rails Tutorial
  is a project to make a book and screencasts to teach web development with
  %a{href: "http://rubyonrails.org/"} Ruby on Rails
  This is the sample application for the tutorial.

app/views/static_pages/contact.html.haml
= provide(:title, 'Contact')
%h1 Contact
%p
  Contact Ruby on Rails Tutorial about the sample app at the
  %a{href: "http://railstutorial.jp/contact"} contact page

app/views/static_pages/help.html.haml
%h1 Help
%p 
  Get help on the Ruby on Rails Tutorial at the
  %a{href: "http://railstutorial.jp/help"} Rails Tutorial  help section
  To get help on this sample app, see the
  %a{href: "http://railstutorial.jp"} 
    %em Ruby on Rails Tutorial
  book

app/views/static_pages/home.html.haml
.center.hero-unit 
  %h1 Welcome to Sample App
  %h2
    This is the home page for the
    %a{href: "http://www.railstutorial.org/"}Ruby on Rails Tutorial 
    sample application.
  = link_to "Sign up now!",signup_path, class: "btn btn-large btn-primary"

= link_to image_tag("rails.png", alt: "Rails"),'http://rubyonrails.org/'

app/views/static_pages/modern.html.haml
%header.header
  %h1.logo=link_to 'Sample Site', '/modern'
  %nav.global-nav
    %ul
      %li.nav-item.active=link_to 'HOME','#'
      %li.nav-item.active=link_to 'ABOUT','#'
      %li.nav-item.active=link_to 'NEWS','#'
      %li.nav-item.active=link_to 'TOPICS','#'
      %li.nav-item.active=link_to 'DOCS','#'
      %li.nav-item.active=link_to 'BLOG','#'
  .wrapper.clearfix
    .main
    .sidemenu
%footer.footer

app/views/static_pages/modern_retry.html.haml
%header.header
  %h1.logo=link_to 'Sample Site', '/modern'
  %nav.global-nav
    %ul
      %li.nav-item.active=link_to 'HOME','#'
      %li.nav-item=link_to 'ABOUT','#'
      %li.nav-item=link_to 'NEWS','#'
      %li.nav-item=link_to 'TOPICS','#'
      %li.nav-item=link_to 'DOCS','#'
      %li.nav-item=link_to 'BLOG','#'
.wrapper.clearfix
  .main
    %h2.hidden HOT TOPIC
    = link_to '#', class: 'hot-topic clearfix' do
      = image_tag("hot-topic.jpg", alt: "コーディング画面", class: 'image')
      .content
        %h3.title
          実務で使えるHTML/CSS
          %br モダンコーディングTIPS           
        %p.desc 
          Webフロントエンドの進化の勢いはとどまるところを知りません。新しい要素が増えて大幅に表現力が広がったHTML5/CSS3を活用して...
        %time.date{datetime: "2015-09-01"} 2015-09-01 TUE
    %h2.heading NEWS
    %ul.scroll-list
      %li.scroll-item
        = link_to '#' do
          %time.date{datetime: "2015-08-23"} 2015-08-23 SUN
          %span.category.news NEWS
          %span.title         WORKSを更新しました。
      %li.scroll-item
        = link_to '#' do
          %time.date{datetime: "2015-08-12"} 2015-08-12 WED
          %span.category TOPIC
          %span.title CSSでここまでできる！？ホントに使えるCSSセレクタ10選！
      %li.scroll-item
        = link_to '#' do
          %time.date{datetime: "2015-08-04"} 2015-08-04 TUE
          %span.category.news TOPIC
          %span.title         TOPICSを更新しました。
      %li.scroll-item
        = link_to '#' do
          %time.date{datetime: "2015-07-25"} 2015-07-25 SAT
          %span.category      TOPIC
          %span.title         CSSコーディングと切っても切れないWebブラウザのシェア動向をチェックしよう
      %li.scroll-item
        = link_to '#' do
          %time.date{datetime: "2015.07.09"} 2015.07.09 THU
          %span.category TOPIC
          %span.title         HTML5の新しい属性で手軽にフォームバリデーション
      %li.scroll-item
        = link_to '#' do
          %time.date{datetime: "2015-06-30"} 2015.06.30 TUE
          %span.category.news NEWS
          %span.title         WORKSを更新しました。  
    %h2.hidden ARTICLES
    .clearfix
      = link_to '#', class: 'article-box' do
        %h3.title 実務で使えるHTML/CSSモダンコーディングTIPS
        %p.desc 新しい要素が増えて大幅に表現力が広がったHTML5/CSS3を活用し、モダンなコーディングにチャレンジしましょう！
        %time.date{datetime: "2015-06-17"} 2015-06-17 WED
        = image_tag("article.jpg", alt: "コーディング画面", class: 'image')
      = link_to '#', class: 'article-box' do
        %h3.title 実務で使えるHTML/CSSモダンコーディングTIPS
        %p.desc 新しい要素が増えて大幅に表現力が広がったHTML5/CSS3を活用し、モダンなコーディングにチャレンジしましょう！
        %time.date{datetime: "2015-06-17"} 2015-06-17 WED
        = image_tag("article.jpg", alt: "コーディング画面", class: 'image')
      = link_to '#', class: 'article-box' do
        %h3.title 実務で使えるHTML/CSSモダンコーディングTIPS
        %p.desc 新しい要素が増えて大幅に表現力が広がったHTML5/CSS3を活用し、モダンなコーディングにチャレンジしましょう！
        %time.date{datetime: "2015-06-17"} 2015-06-17 WED
        = image_tag("article.jpg", alt: "コーディング画面", class: 'image')
      = link_to '#', class: 'article-box' do
        %h3.title 実務で使えるHTML/CSSモダンコーディングTIPS
        %p.desc 新しい要素が増えて大幅に表現力が広がったHTML5/CSS3を活用し、モダンなコーディングにチャレンジしましょう！
        %time.date{datetime: "2015-06-17"} 2015-06-17 WED
        = image_tag("article.jpg", alt: "コーディング画面", class: 'image')
  .sidemenu
    %h2.heading RANKING
    %ol.ranking
      %li.ranking-item
        =link_to '#' do
          = image_tag("ranking.jpg", alt:"グラフの画像", class: 'image')
          %span.order
          %p.text HTML/CSSコーディングと切っても切れないWebブラウザのシェア動向をチェックしよう
      %li.ranking-item
        =link_to '#' do
          = image_tag("ranking.jpg", alt:"グラフの画像", class: 'image')
          %span.order
          %p.text TOPICSを更新しました。
      %li.ranking-item
        =link_to '#' do
          = image_tag("ranking.jpg", alt:"グラフの画像", class: 'image')
          %span.order
          %p.text HTML/CSSコーディングと切っても切れないWebブラウザのシェア動向をチェックしよう
      %li.ranking-item
        =link_to '#' do
          = image_tag("ranking.jpg", alt:"グラフの画像", class: 'image')
          %span.order
          %p.text HTML5の新しい属性で手軽にフォームバリデーション
      %li.ranking-item
        =link_to '#' do
          = image_tag("ranking.jpg", alt:"グラフの画像", class: 'image')
          %span.order
          %p.text WORKSを更新しました。
    %h2.heading DOCUMENTS
    %ul.documents
      %li
        %h3.title HTML5
        %ul
          %li=link_to '追加された要素','#'
          %li=link_to '削除された要素','#'
          %li=link_to '意味が変わった要素','#'
          %li=link_to 'HTMLのコンテンツモデル','#'
      %li
        %h3.title  CSS3
        %ul
          %li=link_to '追加されたプロパティ','#'
          %li=link_to '追加されたセレクタ','#'
          %li=link_to '追加された単位素','#'
      %li
        %h3.title  JavaScript
        %ul
          %li=link_to 'JavaScriptの言語仕様','#'
          %li=link_to 'ECMAScriptとは？','#'
          %li=link_to 'jQueryとは？','#'
      %li
        %h3.title  Sass, Less, Stylus
        %p 準備中
      %li
        %h3.title  TypeScript
        %p 準備中
    %h2.hidden SEARCH
    %form.search-box
      %input.search-input{type: 'text', name:'seach', placeholder:'SEARCH'}
      %input.search-button{type: 'submit', value:'検索'}
      %p.text サイト内の文章を検索できます。         
%footer.footer
  %ul.horizontal-list
    %li.horizontal-item=link_to 'ABOUT ME','#'
    %li.horizontal-item=link_to 'SITE MAP','#'
    %li.horizontal-item=link_to 'SNS','#'
    %li.horizontal-item=link_to 'CONTACT','#'
  %p.copyright Copyright © 2015 SAMPLE SITE

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th Name
      %th Email
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.email
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
= provide(:title, 'Sign Up')
%h1 Sign Up
%p Find me in app/views/users/new.html.erb

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path